### ISSUE TITLE
Wrong Purchase/Sale Quantity accounted

### ISSUE THREAD

**Issue by Zroyx** [Ascension-Addons/TradeSkillMaster#6]
### Description

This TSM port will account for the wrong quantity/money value. 

### Realm

Seasonal

### Tested with only this addon

- [X] Yes
- [ ] No

### Reproduction Steps

Buy 1 Jaggal Clam Meat for price X, retrieve it from the mailbox. You now got a entry in the database for 1 Jaggal Clam Meat costing X. Now buy a stack of Jaggal Clam Meat for example a stack of 5 costing X each resulting in a total price of Y. 

Retrieve it from the mailbox, Now u got a second entry in the database, also for only 1 Jaggal Clam Meat costing now Y instead of X. -> messing up every operation,custom price source using any form of AVGBUY.  

Same is true for sale value.  Here a screenshot of the example. (the base price was not the same on both but still lower price was stack of 1 higher price stack of 5 resulting is roughly 500% of the "per item" price tag. 

### Screenshots

Screenshot of the example, not 100% same base values on the purchases but still lower value for 1 higher value for 5 -> both accounted as quantity 1. Error also confirmed from Xan in the discord.

![Screenshot 2023-09-07 005729](https://github.com/Ascension-Addons/TradeSkillMaster/assets/144290330/25941691-28ee-4ea5-874e-4947afdb0673)

**Comment by Xan-Asc** [comment]
![image](https://github.com/Ascension-Addons/TradeSkillMaster/assets/119889093/80a76895-56ec-44cf-8b4c-026604c4762c)

relevant discussion from the version of TSM this is based on.

**Comment by Zroyx** [comment]
Yea TSM was a Cata thing didnt know there was such a limitation :(

**Comment by andrew6180** [comment]
should be fixed with #7
